name: Release

on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Carthage archive
        run: ./scripts/carthage-archive.sh
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: RxCombine ${{ github.ref_name }}
          files: RxCombine.framework.zip
